version: "3"
services:
  client-app:
    image: client-app
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - resultado-busquedas-api

  api-server:
    image: api-server
    build: ./server/
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    networks:
      - resultado-busquedas-api

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "27017:27017"
    networks:
      - resultado-busquedas-api
networks:
  resultado-busquedas-api:
    driver: bridge
